### ISSUE TITLE
Snippet call doesn't work in the latest version

### ISSUE THREAD

**Issue by vallev** [DashMedia/modx-google-map#1]
Hello!
I was unable to successfully run googleMap as a snippet after the last update because it doesn't fetch my Google Maps API key right. I tried using the system setting for API key as well as typing it as a snippet option with no luck. It shows me `...&key=4` every time. 
As a workaround I added `$settings['key'] = $scriptProperties['key'];` at line 46 in the snippet and it started to work fine, but I wouldn't call this a fix. 
By the way, I can't see anywhere $scriptProperties being parsed, and as far as I know snippet calls don't use $options array. So how it supposed to work then...?

**Comment by JayCarney** [comment]
Thanks for letting me know. The `$options` array is used if you use the snippet as an output filter on a tv (containing an address) such as:

```
<img src="[[*tvAddress:googleMap=`w=425,h=300,z=16,key=xxxxxxxxxxx,sensor=0,marker=1`]]" />
```

**Comment by vallev** [comment]
Yes, when I use the snippet as an output filter everything works fine. I asked about the `$options` array because snippets use the $scriptProperties array so I wonder how it should work without parsing it. Good luck! ;)
